package isadbtool.gui.dlg;

import isadbtool.blogic.BLObject;
import isadbtool.blogic.conceptual.ConceptualEntity;
import isadbtool.blogic.conceptual.ConceptualSimpleAttribute;
import isadbtool.gui.drawobjs.DraggableObj;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JFrame;

public class ObjectSelectorDLG extends javax.swing.JDialog {
  boolean okExitCode;
  ArrayList<String> displayedNamesList;
  ArrayList<String> internalNamesList;

  public ObjectSelectorDLG(JFrame parent,
          Collection<? extends BLObject> objects, String title) {
    super(parent, true);
    initComponents();
    this.setTitle(title);

    valuesComboBox.removeAllItems();
    displayedNamesList = new ArrayList();
    internalNamesList = new ArrayList();
    Set<BLObject> temp = new TreeSet(new Comparator<BLObject>() {
      @Override
      public int compare(BLObject o1, BLObject o2) {
        return o1.getDisplayedName()
                .compareTo(o2.getDisplayedName());
      }
    });
    for (BLObject c : objects) {
      temp.add(c);
    }
    for (BLObject c : temp) {      
      displayedNamesList.add(c.getDisplayedName());
      internalNamesList.add(c.getInternalName());
    }
    for (String item : displayedNamesList) {
      valuesComboBox.addItem(item);
    }
    okExitCode = false;
    setLocationRelativeTo(parent);
    setVisible(true);
  }
  
  private int getSelectedIndex() {
    return valuesComboBox.getSelectedIndex();
  }

  public String getSelectedDisplayedName() {
    return displayedNamesList.get(getSelectedIndex());
  }
  
  public String getSelectedInternalName() {
    return internalNamesList.get(getSelectedIndex());
  }

  public boolean isOkExitCode() {
    return okExitCode;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    dismissButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    valuesComboBox = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    dismissButton.setText("Dismiss");
    dismissButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dismissButtonActionPerformed(evt);
      }
    });

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    valuesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(valuesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(dismissButton)))
        .addGap(0, 15, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(valuesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(okButton)
          .addComponent(dismissButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    // TODO add your handling code here:
    okExitCode = true;
    this.setVisible(false);
  }//GEN-LAST:event_okButtonActionPerformed

  private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
    // TODO add your handling code here:
    okExitCode = false;
    this.setVisible(false);
  }//GEN-LAST:event_dismissButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton dismissButton;
  private javax.swing.JButton okButton;
  private javax.swing.JComboBox<String> valuesComboBox;
  // End of variables declaration//GEN-END:variables
}
