package isadbtool.gui.dlg;

import isadbtool.gui.RunTimeParams;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTextField;

public class PreferencesDLG extends javax.swing.JDialog {
  boolean okExitCode;

  public PreferencesDLG(JFrame theGUI) {
    super(theGUI, true);
    this.setLocation(theGUI.getLocation());
    okExitCode = false;
    initComponents();
    this.projectsDir.setEditable(false);
    this.xmlDir.setEditable(false);
    this.imagesDir.setEditable(false);
    
    for (String s : RunTimeParams.supportedTypes()) {
      this.defType.addItem(s);
    }
  }
  
  public Boolean getOverlappedGeneralizations() {
    return overlappedGeneralizations.isSelected();
  }

  public void setOverlappedGeneralizations(Boolean value) {
    this.overlappedGeneralizations.setSelected(value);
  }
  
  public void setProjectsDir(String theDIR) {
    projectsDir.setText(theDIR);
  }
  
  public String getProjectsDir() {
    return projectsDir.getText().trim();
  }
  
  public void setXmlDir(String theDIR) {
    xmlDir.setText(theDIR);
  }
  
  public void setImagesDir(String theDIR) {
    imagesDir.setText(theDIR);
  }

  public void setEntDefPrefix(String entPrefix) {
    entDefPrefix.setText(entPrefix);
  }

  public void setRelDefPrefix(String relPrefix) {
    relDefPrefix.setText(relPrefix);
  }  
  
  public void setDefaultType(String defautType) {
    defType.setSelectedItem(defautType);
  }  
  
  public String getXmlDir() {
    return xmlDir.getText().trim();
  }  
  
  public String getImagesDir() {
    return imagesDir.getText().trim();
  }

  public String getEntDefPrefix() {
    return entDefPrefix.getText().trim();
  }

  
  public String getRelDefPrefix() {
    return relDefPrefix.getText().trim();
  }

  public String getDefaultType() {
    return (String) defType.getSelectedItem();
  }
  
  public boolean isOkExitCode() {
    return okExitCode;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    relDefPrefix = new javax.swing.JTextField();
    entDefPrefix = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    projectsDir = new javax.swing.JTextField();
    selectProjectsDir = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    defType = new javax.swing.JComboBox<>();
    overlappedGeneralizations = new javax.swing.JCheckBox();
    jLabel5 = new javax.swing.JLabel();
    imagesDir = new javax.swing.JTextField();
    selectImagesDir = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    xmlDir = new javax.swing.JTextField();
    selectXMLDir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
    layout.columnWidths = new int[] {0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0};
    layout.rowHeights = new int[] {0, 17, 0, 17, 0, 17, 0, 17, 0, 17, 0};
    getContentPane().setLayout(layout);

    okButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 10;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(okButton, gridBagConstraints);

    cancelButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 10;
    gridBagConstraints.gridy = 10;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(cancelButton, gridBagConstraints);

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText("Projects Dir");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    getContentPane().add(jLabel1, gridBagConstraints);

    jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Relationship Default Prefix");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(jLabel2, gridBagConstraints);

    relDefPrefix.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    relDefPrefix.setPreferredSize(new java.awt.Dimension(50, 27));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(relDefPrefix, gridBagConstraints);

    entDefPrefix.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(entDefPrefix, gridBagConstraints);

    jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    jLabel3.setText("Entity Default Prefix");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(jLabel3, gridBagConstraints);

    projectsDir.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    getContentPane().add(projectsDir, gridBagConstraints);

    selectProjectsDir.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    selectProjectsDir.setText("Select");
    selectProjectsDir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectProjectsDirActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 10;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(selectProjectsDir, gridBagConstraints);

    jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Default Type");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(jLabel4, gridBagConstraints);

    defType.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(defType, gridBagConstraints);

    overlappedGeneralizations.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    overlappedGeneralizations.setText("Overlapped Generaliztions");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(overlappedGeneralizations, gridBagConstraints);

    jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText("Images Dir");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(jLabel5, gridBagConstraints);

    imagesDir.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(imagesDir, gridBagConstraints);

    selectImagesDir.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    selectImagesDir.setText("Select");
    selectImagesDir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectImagesDirActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 10;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(selectImagesDir, gridBagConstraints);

    jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel6.setText("XML Dir");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(jLabel6, gridBagConstraints);

    xmlDir.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    xmlDir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        xmlDirActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(xmlDir, gridBagConstraints);

    selectXMLDir.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    selectXMLDir.setText("Select");
    selectXMLDir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectXMLDirActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 10;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(selectXMLDir, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    // TODO add your handling code here:
    okExitCode = false;
    this.setVisible(false);
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    okExitCode = true;
    /*theGUI.rtp.defaultProjectsDIR = projectsDir.getText().trim();
    theGUI.rtp.defaultImagesDIR = imagesDir.getText().trim();
    theGUI.rtp.entDefPrefix = entDefPrefix.getText().trim();
    theGUI.rtp.relDefPrefix = relDefPrefix.getText().trim();
    theGUI.rtp.defaultType = (String) defType.getSelectedItem();
    theGUI.rtp.allowOverlappedGeneralization = overlappedGeneralizations.isSelected();
    theGUI.getConceptualArea().updateConceptualgeneralizations();*/
    this.setVisible(false);
  }//GEN-LAST:event_okButtonActionPerformed

  private void selectProjectsDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProjectsDirActionPerformed
    // TODO add your handling code here:
    JFileChooser chooser = new JFileChooser(projectsDir.getText().trim());
    chooser.setDialogTitle("Select Default Directory");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      projectsDir.setText(chooser.getSelectedFile().getAbsolutePath());
    }
  }//GEN-LAST:event_selectProjectsDirActionPerformed

  private void selectImagesDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectImagesDirActionPerformed
    // TODO add your handling code here:
    JFileChooser chooser = new JFileChooser(imagesDir.getText().trim());
    chooser.setDialogTitle("Select Imeges Directory");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      imagesDir.setText(chooser.getSelectedFile().getAbsolutePath());
    }
  }//GEN-LAST:event_selectImagesDirActionPerformed

  private void xmlDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmlDirActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_xmlDirActionPerformed

  private void selectXMLDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectXMLDirActionPerformed
    // TODO add your handling code here:
    JFileChooser chooser = new JFileChooser(xmlDir.getText().trim());
    chooser.setDialogTitle("Select Imeges Directory");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      xmlDir.setText(chooser.getSelectedFile().getAbsolutePath());
    }
  }//GEN-LAST:event_selectXMLDirActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JComboBox<String> defType;
  private javax.swing.JTextField entDefPrefix;
  private javax.swing.JTextField imagesDir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JButton okButton;
  private javax.swing.JCheckBox overlappedGeneralizations;
  private javax.swing.JTextField projectsDir;
  private javax.swing.JTextField relDefPrefix;
  private javax.swing.JButton selectImagesDir;
  private javax.swing.JButton selectProjectsDir;
  private javax.swing.JButton selectXMLDir;
  private javax.swing.JTextField xmlDir;
  // End of variables declaration//GEN-END:variables
}
