package isadbtool.gui.notes;

public class MyFontChooser extends javax.swing.JDialog {
  private static final String[] DEFAULT_FONT_SIZE_STRINGS =
    {
        "8", "9", "10", "11", "12", "14", "16", "18", "20",
        "22", "24", "26", "28", "36", "48", "72",
    };
  boolean okExitCode;  

  public MyFontChooser(java.awt.Frame parent, Integer size) {
    super(parent, true);
    initComponents();
    okExitCode = false;
    sizeComboBox.removeAllItems();
    for (String s : DEFAULT_FONT_SIZE_STRINGS)
      sizeComboBox.addItem(s);
    sizeComboBox.setSelectedItem(size.toString());
  }

  public boolean isOkExitCode() {
    return okExitCode;
  }
  
  public Integer getFontSize() {
    return Integer.parseInt((String) sizeComboBox.getSelectedItem());
  }
  
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    sizeComboBox = new javax.swing.JComboBox<>();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
    layout.columnWidths = new int[] {0, 16, 0, 16, 0};
    layout.rowHeights = new int[] {0, 17, 0};
    getContentPane().setLayout(layout);

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
    jLabel1.setText("Font size");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    getContentPane().add(jLabel1, gridBagConstraints);

    sizeComboBox.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
    sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    getContentPane().add(sizeComboBox, gridBagConstraints);

    okButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    getContentPane().add(okButton, gridBagConstraints);

    cancelButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    getContentPane().add(cancelButton, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    // TODO add your handling code here:
    okExitCode = true;
    setVisible(false);
  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    // TODO add your handling code here:
    okExitCode = false;
    setVisible(false);
  }//GEN-LAST:event_cancelButtonActionPerformed

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton okButton;
  private javax.swing.JComboBox<String> sizeComboBox;
  // End of variables declaration//GEN-END:variables
}
